# Generated by Django 3.0.5 on 2020-05-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='stream',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=250),
        ),
    ]
